server:
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  security:
    public-api-docs: false

file:
  base-url: ${FILE_BASE_URL}

logging:
  level:
    root: info
    com.campusone: ${APP_LOG_LEVEL:info}
